version: '3.8'

services:
  mongodb:
    image: mongo:5.0.2
    restart: unless-stopped
    env_file: ./backend/config/config.env
    environment:
      - MONGO_INITDB_ROOT_USERNAME=$MONGODB_USER
      - MONGO_INITDB_ROOT_PASSWORD=$MONGODB_PASSWORD
    ports:
      - $MONGODB_LOCAL_PORT:$MONGODB_DOCKER_PORT
    volumes:
      - db:/data/db
  backend:
    depends_on:
      - mongodb
    build: 
      context: backend
      dockerfile: Dockerfile
    ports:
      - '4000:4000'
  frontend:
    build: 
      context: frontend
      dockerfile: Dockerfile
    ports:
      - '3000:3000'